// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService streams the managed browser into the inspector panel and
 * injects panel input back over CDP. The browser process is launched by the
 * pi-desk-browser extension; attaching is best-effort and read-only until
 * the panel is open.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Click injects a mouse press/release at CSS-pixel page coordinates.
 */
export function Click(request: domain$0.BrowserClickRequest): $CancellablePromise<void> {
    return $Call.ByID(3846639650, request);
}

/**
 * Key injects a named key press, e.g. "Enter", "ctrl+shift+T".
 */
export function Key(request: domain$0.BrowserKeyRequest): $CancellablePromise<void> {
    return $Call.ByID(2681832649, request);
}

/**
 * Scroll injects a mouse wheel event at CSS-pixel page coordinates.
 */
export function Scroll(request: domain$0.BrowserWheelRequest): $CancellablePromise<void> {
    return $Call.ByID(3938158811, request);
}

/**
 * Start attaches to the managed browser and begins the screencast.
 */
export function Start(): $CancellablePromise<domain$0.BrowserStatus> {
    return $Call.ByID(4115535482);
}

/**
 * Stop detaches from the managed browser. The browser itself keeps running.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(984027482);
}

/**
 * Type inserts text into the focused element via Input.insertText.
 */
export function Type(request: domain$0.BrowserTextInputRequest): $CancellablePromise<void> {
    return $Call.ByID(328217778, request);
}
