// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagedSkillService edits only Pi-owned global and project skill roots. Other
 * harness directories, including ~/.agents/skills, remain read-only to Pi Desk.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function CreateManagedSkill(request: domain$0.CreateManagedSkillRequest): $CancellablePromise<domain$0.ManagedSkill> {
    return $Call.ByID(2916283716, request);
}

export function DeleteManagedSkill(request: domain$0.ManagedSkillRequest): $CancellablePromise<void> {
    return $Call.ByID(3344074707, request);
}

export function GetManagedSkill(request: domain$0.ManagedSkillRequest): $CancellablePromise<domain$0.ManagedSkill> {
    return $Call.ByID(501707140, request);
}

export function ListManagedSkills(request: domain$0.ListManagedSkillsRequest): $CancellablePromise<domain$0.ManagedSkillSnapshot> {
    return $Call.ByID(126764837, request);
}

export function UpdateManagedSkill(request: domain$0.UpdateManagedSkillRequest): $CancellablePromise<domain$0.ManagedSkill> {
    return $Call.ByID(589097169, request);
}
