// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * McpConfigService edits Pi's global mcp.json. Imported host and project
 * configurations are deliberately outside Pi Desk's writable surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function DeleteMcpServer(request: domain$0.McpServerRequest): $CancellablePromise<void> {
    return $Call.ByID(1555823142, request);
}

export function GetMcpServer(request: domain$0.McpServerRequest): $CancellablePromise<domain$0.McpServer> {
    return $Call.ByID(246355267, request);
}

export function ListMcpServers($0: domain$0.ListMcpServersRequest): $CancellablePromise<domain$0.McpConfigSnapshot> {
    return $Call.ByID(177210300, $0);
}

export function UpsertMcpServer(request: domain$0.UpsertMcpServerRequest): $CancellablePromise<domain$0.McpServer> {
    return $Call.ByID(3113072854, request);
}
