// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * McpConfigService edits Pi's global and trusted-workspace MCP configuration.
 * Imported host configurations remain outside Pi Desk's writable surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function DeleteMcpServer(request: domain$0.McpServerRequest): $CancellablePromise<void> {
    return $Call.ByID(1555823142, request);
}

/**
 * GetMcpEngineStatus reports whether pi-mcp-adapter is installed as a global
 * Pi package and which shared config files pi-mcp-adapter also reads alongside
 * the Pi-owned global and project override files this service edits.
 */
export function GetMcpEngineStatus(request: domain$0.McpEngineStatusRequest): $CancellablePromise<domain$0.McpEngineStatus> {
    return $Call.ByID(2796697444, request);
}

export function GetMcpServer(request: domain$0.McpServerRequest): $CancellablePromise<domain$0.McpServer> {
    return $Call.ByID(246355267, request);
}

/**
 * ListImportableMcpServers scans other hosts' MCP configuration files (JSON
 * only; Codex's TOML is deliberately out of scope) for importable servers.
 */
export function ListImportableMcpServers(): $CancellablePromise<domain$0.McpImportCandidate[] | null> {
    return $Call.ByID(4045350737);
}

export function ListMcpServers(request: domain$0.ListMcpServersRequest): $CancellablePromise<domain$0.McpConfigSnapshot> {
    return $Call.ByID(177210300, request);
}

/**
 * TestMcpServer starts the current editor definition without saving it, then
 * asks the same MCP client library used by pi-mcp-adapter for server metadata.
 */
export function TestMcpServer(request: domain$0.TestMcpServerRequest): $CancellablePromise<domain$0.McpServerTestResult> {
    return $Call.ByID(3051223387, request);
}

export function UpsertMcpServer(request: domain$0.UpsertMcpServerRequest): $CancellablePromise<domain$0.McpServer> {
    return $Call.ByID(3113072854, request);
}
