// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OrphanSessionService is the local-only read/delete/export path for SSH-anchor transcripts and owns no
 * SSH connection, workspace capability, Repository, Terminal, or Pi session.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function DeleteOrphanSession(request: domain$0.DeleteSessionRequest): $CancellablePromise<domain$0.DeletedSession> {
    return $Call.ByID(562159035, request);
}

export function ExportOrphanSession(request: domain$0.ExportOrphanSessionRequest): $CancellablePromise<void> {
    return $Call.ByID(2446961672, request);
}

export function GetOrphanSessionSnapshot(request: domain$0.SessionSnapshotRequest): $CancellablePromise<domain$0.SessionSnapshot> {
    return $Call.ByID(173864750, request);
}

export function ListOrphanSessions(): $CancellablePromise<domain$0.OrphanSessionSummary[] | null> {
    return $Call.ByID(350314263);
}

export function RestoreOrphanSession(request: domain$0.RestoreOrphanSessionRequest): $CancellablePromise<void> {
    return $Call.ByID(3428493908, request);
}
