// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function InstallPiDeskTodo(): $CancellablePromise<domain$0.PiDeskTodoInstallResult> {
    return $Call.ByID(412651075);
}

export function ListExtensions(): $CancellablePromise<domain$0.PiExtensionSnapshot> {
    return $Call.ByID(41749424);
}

export function RemovePiDeskTodo(): $CancellablePromise<void> {
    return $Call.ByID(1327243640);
}
