// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PromptTemplateService edits Pi's documented prompt template locations. It does
 * not maintain a second registry, so Pi remains the source of truth for commands.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function DeletePromptTemplate(request: domain$0.PromptTemplateRequest): $CancellablePromise<void> {
    return $Call.ByID(2237414659, request);
}

export function GetPromptTemplate(request: domain$0.PromptTemplateRequest): $CancellablePromise<domain$0.PromptTemplate> {
    return $Call.ByID(546095552, request);
}

export function ListPromptTemplates(request: domain$0.ListPromptTemplatesRequest): $CancellablePromise<domain$0.PromptTemplateSnapshot> {
    return $Call.ByID(458660181, request);
}

export function UpsertPromptTemplate(request: domain$0.UpsertPromptTemplateRequest): $CancellablePromise<domain$0.PromptTemplate> {
    return $Call.ByID(2578801691, request);
}
