// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RemoteWorkspaceService is the Wails-safe facade for explicit SSH connect and
 * root trust. It accepts no executable path, SSH option, command, or platform.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function ConnectRemoteTarget(request: domain$0.ConnectRemoteTargetRequest): $CancellablePromise<string> {
    return $Call.ByID(3925384778, request);
}

export function DecideRemoteRoot(request: domain$0.DecideRemoteRootRequest): $CancellablePromise<domain$0.WorkspaceSummary> {
    return $Call.ByID(1339191011, request);
}

export function DisconnectRemoteTarget(request: domain$0.RemoteTargetRequest): $CancellablePromise<void> {
    return $Call.ByID(3258921564, request);
}

export function DiscoverRemoteTargets(): $CancellablePromise<domain$0.RemoteAliasSummary[] | null> {
    return $Call.ByID(95689130);
}

export function ListRemoteTargets(): $CancellablePromise<domain$0.RemoteTargetSummary[] | null> {
    return $Call.ByID(2522764147);
}

export function OpenRemoteWorkspace(request: domain$0.WorkspaceRequest): $CancellablePromise<domain$0.WorkspaceSummary> {
    return $Call.ByID(4173390316, request);
}

export function PrepareRemoteRoot(request: domain$0.PrepareRemoteRootRequest): $CancellablePromise<domain$0.RemoteRootCandidate> {
    return $Call.ByID(4193010550, request);
}

export function RemoveRemoteTarget(request: domain$0.RemoteTargetRequest): $CancellablePromise<void> {
    return $Call.ByID(497786182, request);
}

export function ResumeRemoteWorkspace(request: domain$0.ResumeRemoteWorkspaceRequest): $CancellablePromise<domain$0.WorkspaceSummary> {
    return $Call.ByID(2248050773, request);
}
