// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Branches(request: domain$0.RepositoryRequest): $CancellablePromise<domain$0.GitBranchInventory> {
    return $Call.ByID(1079385008, request);
}

/**
 * ClipboardFiles returns references to local files: workspace files use
 * workspace-relative paths and other files use absolute paths. Ordinary
 * files are never read, uploaded, moved or copied by this operation.
 */
export function ClipboardFiles(request: domain$0.RepositoryRequest): $CancellablePromise<domain$0.RepositoryFile[] | null> {
    return $Call.ByID(1894275181, request);
}

export function Diff(request: domain$0.RepositoryFileRequest): $CancellablePromise<domain$0.RepositoryFileDiff> {
    return $Call.ByID(226261371, request);
}

export function OpenFile(request: domain$0.RepositoryFileRequest): $CancellablePromise<void> {
    return $Call.ByID(323633594, request);
}

export function OpenFileWith(request: domain$0.RepositoryFileRequest): $CancellablePromise<void> {
    return $Call.ByID(1363683622, request);
}

export function PreviewFile(request: domain$0.RepositoryFileRequest): $CancellablePromise<domain$0.RepositoryFilePreview> {
    return $Call.ByID(698487166, request);
}

export function RevealFile(request: domain$0.RepositoryFileRequest): $CancellablePromise<void> {
    return $Call.ByID(2221038535, request);
}

export function RollbackSessionFile(request: domain$0.RollbackSessionFileRequest): $CancellablePromise<void> {
    return $Call.ByID(3038729986, request);
}

export function SaveFileAs(request: domain$0.RepositorySaveFileRequest): $CancellablePromise<void> {
    return $Call.ByID(4265531131, request);
}

export function SessionFileChanges(request: domain$0.SessionFileChangesRequest): $CancellablePromise<domain$0.SessionFileChanges> {
    return $Call.ByID(3091344059, request);
}

export function Snapshot(request: domain$0.RepositoryRequest): $CancellablePromise<domain$0.RepositorySnapshot> {
    return $Call.ByID(2696320296, request);
}
