// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Resize(request: domain$0.TerminalResizeRequest): $CancellablePromise<void> {
    return $Call.ByID(4278006652, request);
}

export function Snapshot(request: domain$0.TerminalRequest): $CancellablePromise<domain$0.TerminalState> {
    return $Call.ByID(1851444656, request);
}

export function Start(request: domain$0.StartTerminalRequest): $CancellablePromise<domain$0.TerminalState> {
    return $Call.ByID(96851080, request);
}

export function Stop(request: domain$0.TerminalRequest): $CancellablePromise<void> {
    return $Call.ByID(3023397612, request);
}

export function Write(request: domain$0.TerminalWriteRequest): $CancellablePromise<void> {
    return $Call.ByID(3883351155, request);
}
